#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace ConjureApp.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'BuildVersion'
    /// </summary>
    public partial class BuildVersion
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildVersion"/> class.
        /// </summary>
        public BuildVersion()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'SystemInformationID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SystemInformationID'.
        /// </value>
        public virtual byte SystemInformationID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Database Version'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Database Version'.
        /// </value>
        public virtual string DatabaseVersion { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'VersionDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'VersionDate'.
        /// </value>
        public virtual DateTime VersionDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ModifiedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ModifiedDate'.
        /// </value>
        public virtual DateTime ModifiedDate { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        #endregion // Generated Relationships
    }
}
