#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace ConjureApp.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'ErrorLog'
    /// </summary>
    public partial class ErrorLog
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ErrorLog"/> class.
        /// </summary>
        public ErrorLog()
        {
            #region Generated Constructor


            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorLogID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorLogID'.
        /// </value>
        public virtual int ErrorLogID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorTime'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorTime'.
        /// </value>
        public virtual DateTime ErrorTime { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'UserName'.
        /// </summary>
        /// <value>
        /// The property value representing column 'UserName'.
        /// </value>
        public virtual string UserName { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorNumber'.
        /// </value>
        public virtual int ErrorNumber { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorSeverity'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorSeverity'.
        /// </value>
        public virtual int? ErrorSeverity { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorState'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorState'.
        /// </value>
        public virtual int? ErrorState { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorProcedure'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorProcedure'.
        /// </value>
        public virtual string? ErrorProcedure { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorLine'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorLine'.
        /// </value>
        public virtual int? ErrorLine { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ErrorMessage'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ErrorMessage'.
        /// </value>
        public virtual string ErrorMessage { get; set; } = default!;

        #endregion // Generated Properties

        #region Generated Relationships

        #endregion // Generated Relationships
    }
}
