#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace ConjureApp.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'Product'
    /// </summary>
    public partial class Product
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Product"/> class.
        /// </summary>
        public Product()
        {
            #region Generated Constructor

            SalesOrderDetails = new System.Collections.ObjectModel.ObservableCollection<SalesOrderDetail>();

            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'ProductID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ProductID'.
        /// </value>
        public virtual int ProductID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Name'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Name'.
        /// </value>
        public virtual string Name { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'ProductNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ProductNumber'.
        /// </value>
        public virtual string ProductNumber { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'Color'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Color'.
        /// </value>
        public virtual string? Color { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'StandardCost'.
        /// </summary>
        /// <value>
        /// The property value representing column 'StandardCost'.
        /// </value>
        public virtual decimal StandardCost { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ListPrice'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ListPrice'.
        /// </value>
        public virtual decimal ListPrice { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Size'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Size'.
        /// </value>
        public virtual string? Size { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Weight'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Weight'.
        /// </value>
        public virtual decimal? Weight { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ProductCategoryID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ProductCategoryID'.
        /// </value>
        public virtual int? ProductCategoryID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ProductModelID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ProductModelID'.
        /// </value>
        public virtual int? ProductModelID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'SellStartDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SellStartDate'.
        /// </value>
        public virtual DateTime SellStartDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'SellEndDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SellEndDate'.
        /// </value>
        public virtual DateTime? SellEndDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'DiscontinuedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'DiscontinuedDate'.
        /// </value>
        public virtual DateTime? DiscontinuedDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ThumbNailPhoto'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ThumbNailPhoto'.
        /// </value>
        public virtual Byte[]? ThumbNailPhoto { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ThumbnailPhotoFileName'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ThumbnailPhotoFileName'.
        /// </value>
        public virtual string? ThumbnailPhotoFileName { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'rowguid'.
        /// </summary>
        /// <value>
        /// The property value representing column 'rowguid'.
        /// </value>
        public virtual Guid Rowguid { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ModifiedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ModifiedDate'.
        /// </value>
        public virtual DateTime ModifiedDate { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="ProductCategory" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="ProductCategory" />.
        /// </value>
        /// <seealso cref="ProductCategoryID" />
        public virtual ProductCategory ProductCategory {get; set; }
        
        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="ProductModel" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="ProductModel" />.
        /// </value>
        /// <seealso cref="ProductModelID" />
        public virtual ProductModel ProductModel {get; set; }
        
        /// <summary>
        /// Gets or sets the navigation collection for entity <see cref="SalesOrderDetail" />.
        /// </summary>
        /// <value>
        /// The the navigation collection for entity <see cref="SalesOrderDetail" />.
        /// </value>
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }

        #endregion // Generated Relationships
    }
}
