#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using System.Collections.Generic;

namespace ConjureApp.Data.Entities
{
    /// <summary>
    /// Entity class representing data for table 'SalesOrderHeader'
    /// </summary>
    public partial class SalesOrderHeader
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SalesOrderHeader"/> class.
        /// </summary>
        public SalesOrderHeader()
        {
            #region Generated Constructor

            SalesOrderDetails = new System.Collections.ObjectModel.ObservableCollection<SalesOrderDetail>();

            #endregion // Generated Constructor
        }

        #region Generated Properties

        /// <summary>
        /// Gets or sets the property value representing column 'SalesOrderID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SalesOrderID'.
        /// </value>
        public virtual int SalesOrderID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'RevisionNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'RevisionNumber'.
        /// </value>
        public virtual byte RevisionNumber { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'OrderDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'OrderDate'.
        /// </value>
        public virtual DateTime OrderDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'DueDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'DueDate'.
        /// </value>
        public virtual DateTime DueDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ShipDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ShipDate'.
        /// </value>
        public virtual DateTime? ShipDate { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Status'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Status'.
        /// </value>
        public virtual byte Status { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'OnlineOrderFlag'.
        /// </summary>
        /// <value>
        /// The property value representing column 'OnlineOrderFlag'.
        /// </value>
        public virtual bool OnlineOrderFlag { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'SalesOrderNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SalesOrderNumber'.
        /// </value>
        public virtual string SalesOrderNumber { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'PurchaseOrderNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'PurchaseOrderNumber'.
        /// </value>
        public virtual string? PurchaseOrderNumber { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'AccountNumber'.
        /// </summary>
        /// <value>
        /// The property value representing column 'AccountNumber'.
        /// </value>
        public virtual string? AccountNumber { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'CustomerID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'CustomerID'.
        /// </value>
        public virtual int CustomerID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ShipToAddressID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ShipToAddressID'.
        /// </value>
        public virtual int? ShipToAddressID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'BillToAddressID'.
        /// </summary>
        /// <value>
        /// The property value representing column 'BillToAddressID'.
        /// </value>
        public virtual int? BillToAddressID { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ShipMethod'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ShipMethod'.
        /// </value>
        public virtual string ShipMethod { get; set; } = default!;

        /// <summary>
        /// Gets or sets the property value representing column 'CreditCardApprovalCode'.
        /// </summary>
        /// <value>
        /// The property value representing column 'CreditCardApprovalCode'.
        /// </value>
        public virtual string? CreditCardApprovalCode { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'SubTotal'.
        /// </summary>
        /// <value>
        /// The property value representing column 'SubTotal'.
        /// </value>
        public virtual decimal SubTotal { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'TaxAmt'.
        /// </summary>
        /// <value>
        /// The property value representing column 'TaxAmt'.
        /// </value>
        public virtual decimal TaxAmt { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Freight'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Freight'.
        /// </value>
        public virtual decimal Freight { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'TotalDue'.
        /// </summary>
        /// <value>
        /// The property value representing column 'TotalDue'.
        /// </value>
        public virtual decimal TotalDue { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'Comment'.
        /// </summary>
        /// <value>
        /// The property value representing column 'Comment'.
        /// </value>
        public virtual string? Comment { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'rowguid'.
        /// </summary>
        /// <value>
        /// The property value representing column 'rowguid'.
        /// </value>
        public virtual Guid Rowguid { get; set; }

        /// <summary>
        /// Gets or sets the property value representing column 'ModifiedDate'.
        /// </summary>
        /// <value>
        /// The property value representing column 'ModifiedDate'.
        /// </value>
        public virtual DateTime ModifiedDate { get; set; }

        #endregion // Generated Properties

        #region Generated Relationships

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="Address" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="Address" />.
        /// </value>
        /// <seealso cref="BillToAddressID" />
        public virtual Address BillToAddress {get; set; }
        
        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="Customer" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="Customer" />.
        /// </value>
        /// <seealso cref="CustomerID" />
        public virtual Customer Customer {get; set; }
        
        /// <summary>
        /// Gets or sets the navigation collection for entity <see cref="SalesOrderDetail" />.
        /// </summary>
        /// <value>
        /// The the navigation collection for entity <see cref="SalesOrderDetail" />.
        /// </value>
        public virtual ICollection<SalesOrderDetail> SalesOrderDetails { get; set; }

        /// <summary>
        /// Gets or sets the navigation property for entity <see cref="Address" />.
        /// </summary>
        /// <value>
        /// The the navigation property for entity <see cref="Address" />.
        /// </value>
        /// <seealso cref="ShipToAddressID" />
        public virtual Address ShipToAddress {get; set; }
        
        #endregion // Generated Relationships
    }
}
