#pragma warning disable IDE0073 // The file header is missing or not located at the top of the file
/** THIS IS AUTOGENERATED BY CONJURE EFX **/
#pragma warning restore IDE0073 // The file header is missing or not located at the top of the file

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ConjureApp.Data
{
    public partial class DataWorkspace : Conjure.BlazorKit.Data.DataWorkspaceBase
    {
        private AdventureWorksLT2017Context? _AdventureWorksLT2017Context;

        public DataWorkspace(Microsoft.Extensions.DependencyInjection.IServiceScopeFactory scopeFactory)
            : base(scopeFactory)
        { }

        public AdventureWorksLT2017Context AdventureWorksLT2017
        {
            get
            {
                if (_AdventureWorksLT2017Context == null)
                {
                    _AdventureWorksLT2017Context = CreateContext<AdventureWorksLT2017Context>();
                    base.AddContext(_AdventureWorksLT2017Context);
                }
                return _AdventureWorksLT2017Context;
            }
        }
    }
}
